.TH STW 1 stw
.SH NAME
stw \- simple X text window
.SH SYNOPSIS
.B stw
.RB [ \-to ]
.RB [ \-g
.IR geometry ]
.RB [ \-c
.IR colors ]
.RB [ \-f
.IR font ]
.RB [ \-a
.IR align ]
.RB [ \-b
.IR borderpx ]
.RB [ \-p
.IR period ]
.RB [ \-A
.IR alpha ]
.RB [ \-r
.IR regexp ]
.IR command
.RI [ arg ...]
.SH DESCRIPTION
.B stw
is a simple X text window
.SH OPTIONS
.TP
.BI \-t
place window on top
.TP
.BI \-o
enable pointer events pass through
.TP
.BI \-g " geometry"
window geometry, see POSITION section
.TP
.BI \-c " colors"
colorscheme, see COLORS section
.TP
.BI \-f " font"
text font in format, supported by fontconfig
.TP
.BI \-a " align"
text alignment.
Must be one of {lrc} for left, right and centered
.TP
.BI \-b " borderpx"
window padding in pixels
.TP
.BI \-p " period"
period between command runs in seconds. 0 will completely disable subcommand restarts and -1 will make them instant. In any case a click on a window will still immediately restart subcommand
.TP
.BI \-A " alpha"
window background alpha value
.TP
.BI \-r " regexp"
regexp to match clickable text
.I command [arg...]
command will be started with provided arguments and it's output
will be displayed in the window

.SH POSITION
To position stw window use -g option. It accepts geometry options in format

    [+-]NUMBER[%]

It is possible to specify corner of the window and offset from it. For example

    -g +100,+50

will position window 100 pixels from the left and 50 pixels from the top of the screen. You can also use negative values to position window from the right or bottom of the screen. For example

    -g -100,-50

will position window 100 pixels from the right and 50 pixels from the bottom of the screen.

Third and fourth options control postion relative to window size. For example

    -g 50%,50%,-50%,-50%

will position window in the center of the screen.

You can skip some options using empty values. For example

    -g ,-0

will position window at the bottom of the screen, same as

    -g 0,-0

.SH COLORS

To specify fg and bg colors use -c option. It accepts named colors and hex values in format '#RRGGBB'. For example

    -c black,white

will set black text on white background. You can repeat pairs to specify fg and bg colors for other colorschemes. For example

    -c black,white,red,green

will set red text on green background for second colorscheme. 

.SH CLICKABLE TEXT

To make text clickable use -r option. It accepts extended POSIX regular expressions. For example

    -r '[[^]]+]'

will make text between square brackets clickable.

Matched text will be highlighted using secondary colorscheme.

Clicking on matched text will restart command with env variable STW_SELECTED set to matched text.

NOTE: Clicking on any other part of the window will still restart command without STW_SELECTED set.

.SH EXAMPLES

Show current date in the center of the screen:

    $ stw -p 1 -x 50% -y 50% -X -50% -Y -50% -F monospace:size=20 date

Show updated packages:

    $ stw -p 0 sh -c 'xbps-install -nSu | cut -d" " -f1 | head -n 20'

.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH SEE ALSO
.BR watch (1)
